name: CI/CD - Microservicio Node.js en DOCKER desplegado en EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/demo-microservice-lab
  APP_PORT: ${{secrets.APP_PORT || 3000}}

jobs:
  ci:
    name: Integracion continua (build y test)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Configuracion Node.js
        uses: actions/setup-node@v4

        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar las pruebas
        run: npm test

      - name: Iniciar sesion en Docker Hub
        run: |
          # Usar las credenciales de token de secret
          echo "${{secrets.DOCKERHUB_TOKEN}} | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Publicar la imagen (latest)
        run: docker push $IMAGE_NAME:latest
  cd:
    name: Entrega y despliegue en EC2
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Instalar cliente SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Configurar llave SSH
        run: |
          # creamos la carpeta .ssh y guardamos la llave privada que tiene secrets
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{secrets.EC2_HOST}}" >> ~/.ssh/know_hosts

      - name: Desplegamos el contenedor en EC2
        env:
          HOST: ${{secrets.EC2_HOST}}
          USER: ${{secrets.EC2_USER}}
          IMAGE: ${{secrets.DOCKERHUB_USERNAME}}/demo-microservice-lab
        run: |
          ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking -l "$USER" "$HOST" << EOF
          set -euxo pipefial
          sudo system start docker
          docker network inspect appnet >/dev/null 2>&1 || docker network create appnet
          docker ps -q filter "name=demo-microservice-lab" | grep -q . && docker stop demo-microservice-lab || true
          docker ps -aq --filter "name=demo-microservice-lab" | grep -q . && docker rm demo-microservice-lab || true
          docker pull $IMAGE
          docker run -d --name demo-microservice-lab --restart unless-stopped --network appnet -p 80:3000 $IMAGE
          EOF
